services:
  tensorflow:
    # image: tensorflow/tensorflow:latest-gpu # Adjust to the TensorFlow version that you need with GPU support
    image: nvcr.io/nvidia/tensorflow:24.05-tf2-py3
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    ipc: host
    shm_size: 32G
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - ${HOME}/dockerx:/dockerx
      - ../src:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    user: "${UID}:${GID}" # Specify user by UID and GID environment variables

